# Python Assignment 22

### Answer 1

The built-in array package in Python provides an array data structure that is more memory efficient than a list. It is useful for storing large data sets that need to be manipulated quickly and efficiently.

### Answer 2

Some Limitations of Array Package:
* The datatype of the array must be specified when array is created, and cannot be changed after array is created.
* The array can hold items of same data types, while list can hold items of different data types.
* The array package does not have as many built-in functions and methods as the list and other data structures in Python.

### Answer 3

* Numpy has a lot of mathematical operator, linear algerbra that is not available in Python array.
* Numpy is more efficient than Python array because it is implemented in C.

### Answer 4

* `empty` function create a create an array of given shape filled with garbage values.
* `zeros` function create an array of given shape with all entries are zero.
* `ones` function create an array of given shape with all entries are one.

### Answer 5

The function like `fromlist, frombytes, fromfile` can construct a array from a respective python object. Like `array.array.fromlist` can create a array from python list object. And one important thing to remember all the items in the list must have same datatype.

In [1]:
from array import array

myList = [1, 2, 3, 4]

myArray = array('i', [])
myArray.fromlist(myList)

myArray

array('i', [1, 2, 3, 4])

### Answer 6

When an numpy array is combined with a single value operand then numpy applies it to all the entries in the array.

In [2]:
import numpy as np

arr = np.array([[1, 2], [2, 4]])

arr * 2                            # here 2 is multipled with all the entries

array([[2, 4],
       [4, 8]])

### Answer 7

When we apply combined operator assign (`+=` or `*=`) with numpy array, first numpy applies the operand to all the entries in the array then the original array is updated with the result. This is same behaviour like `int`, `float`, `str` ... objects.

In [3]:
import numpy as np

arr = np.array([1, 2, 3])

arr *= 2              # operator assign
arr                   # changes are reflected to original array

array([2, 4, 6])

### Answer 8

Yes, numpy array contains string store all entries in a fixed length. If we allocate a longer string then numpy change all the entries according to longer string. Here is an example:

In [4]:
# a numpy array containing string of all same length it data type is U3
np.array(['123', '112', '123', '456', '765', '432', '456'])

array(['123', '112', '123', '456', '765', '432', '456'], dtype='<U3')

In [5]:
# a numpy array containing string of all same length with a longer string and the data type is changed to U7
np.array(['123', '112', '123', '456', '765', '432', '456', '1234567'])

array(['123', '112', '123', '456', '765', '432', '456', '1234567'],
      dtype='<U7')

### Answer 9

When we apply arithmetic operation on two numpy array them numpy applies all the arithmetic operation to element wise, during arithmetic operator the shape of both array must be same.

In [6]:
arr_1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr_2 = np.array([[9, 8, 7], [6, 5, 4], [3, 2, 1]])

arr_1 + arr_2

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

### Answer 10

The boolean array in numpy can be used to get values inside array for which respective value of boolean array is `True`. These boolean array are usefull when we have to apply some condition on array. Here is an example:

In [7]:
arr = np.array([1, 2, 4, 2, 3, 2])

b = arr > 2             # condition give a boolean array when item in array is greater than 2
b                       # boolean array

array([False, False,  True, False,  True, False])

In [8]:
arr[b]

array([4, 3])

### Answer 11

Here are there ways by which we can get standard deviation of a data using python and its library.

In [9]:
import random

# a dataset contains 10000 floating point value in range 1 to 4
data = [random.uniform(1, 4) for i in range(10000)]

First Method Using Custom Function

In [10]:
# Custom function for standard deviation

def standard_deviation(data: list, ddof = 0) -> float:
    '''Return Standard Deviation.'''
    
    length = len(data)
    mean = sum(data) / length
    variance = sum([(point - mean) ** 2 for point in data]) / (length - ddof)
    return (variance) ** 0.5

Second Method Using Numpy Package

In [11]:
import numpy as np

np.std(data, ddof = 1)

0.865415197119109

Third Method Using Statistics Module

In [12]:
import statistics as stats

stats.stdev(data)

0.865415197119109

Order by execution time(fasted first):
* Numpy Module
* Python Function
* Statistics Module

In [13]:
%timeit -n 1000 np.std(data, ddof = 1)

1.34 ms ± 93.9 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [14]:
# custom function
%timeit -n 1000 standard_deviation(data, ddof = 1)

3.56 ms ± 176 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [15]:
%timeit -n 1000 stats.stdev(data)

34.5 ms ± 1.08 ms per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


### Answer 12

The dimensionality of the boolean array depends on the dimension on the array from which it is generated, Here is an example:

In [16]:
# array 2 dimensional array
arr = np.array([[1, 2, 4], [5, 5, 63], [8, 99, 10]])
arr

array([[ 1,  2,  4],
       [ 5,  5, 63],
       [ 8, 99, 10]])

In [17]:
mask = arr > 5
mask

array([[False, False, False],
       [False, False,  True],
       [ True,  True,  True]])

Here you can see the dimension of the boolean mask is same as the dimension of array.

In [18]:
arr.ndim == mask.ndim

True